--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/MrNinja008/BedrockScoreTags
build-by-default: true
branches:
- main
projects:
  BedrockScoreTags:
    path: ""
    lint:
       phpstan: false
...
